version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"

    allow:
      - dependency-name: "ultracite"
      - dependency-name: "@biomejs/biome"

    open-pull-requests-limit: 4 